version: '3.8'

services:
    merchandise-service:
        build: .
        ports:
            - "80:80"

    stock-api:
        image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
        hostname: stock_api
        ports:
            - "8081:81"

    employees-service:
        image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
        hostname: employees-service
        ports:
            - "8082:82"

    supply-service:
        image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
        hostname: supply-service
        ports:
            - "8083:83"

    emailing-service:
        image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
        hostname: emailing-service
        ports:
            - "8084:84"